enableGlobalCache: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-deduplicate.cjs
    spec: "https://raw.githubusercontent.com/eps1lon/yarn-plugin-deduplicate/latest/bin/%40yarnpkg/plugin-deduplicate.js"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-2.1.1.cjs
